version: '3.7'

services:
  n_car_fuel_calc_postgres:
    container_name: n_car_fuel_calc_postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: car_fuel
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/www/car_fuel_calculator/docker-volumes/postgres
    ports:
      - 5432:5432
    networks:
      - car_fuel_cal
    restart: unless-stopped

  n_car_fuel_calc_pgadmin:
    container_name: n_car_fuel_calc_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: izocougar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/www/car_fuel_calculator/docker-volumes/pgadmin
    ports:
      - 5050:80
    networks:
      - car_fuel_cal
    restart: unless-stopped

networks:
  car_fuel_cal:
    driver: bridge

volumes:
  postgres:
  pgadmin: